package entity

type MatchRecordDTO struct {
	MatchID         string
	Player1         string
	Player2         string
	Player3         string
	Player4         string
	Player5         string
	Player6         string
	Player7         string
	Player8         string
	Player9         string
	Player10        string
	EndOfGameResult string
	GameCreation    int64
	GameDuration    int64
}

type MatchPlayerDetailsDTO struct {
	MatchID                        string
	AllInPings                     int
	AssistMePings                  int
	Assists                        int
	BaronKills                     int
	BountyLevel                    int
	ChampExperience                int
	ChampLevel                     int
	ChampionId                     int
	ChampionName                   string
	CommandPings                   int
	ChampionTransform              int
	ConsumablesPurchased           int
	DamageDealtToBuildings         int
	DamageDealtToObjectives        int
	DamageDealtToTurrets           int
	DamageSelfMitigated            int
	Deaths                         int
	DetectorWardsPlaced            int
	DoubleKills                    int
	DragonKills                    int
	EnemyMissingPings              int
	EnemyVisionPings               int
	FirstBloodAssist               bool
	FirstBloodKill                 bool
	FirstTowerAssist               bool
	FirstTowerKill                 bool
	GameEndedInEarlySurrender      bool
	GameEndedInSurrender           bool
	HoldPings                      int
	GetBackPings                   int
	GoldEarned                     int
	GoldSpent                      int
	IndividualPosition             string
	InhibitorKills                 int
	InhibitorTakedowns             int
	InhibitorsLost                 int
	Item0                          int
	Item1                          int
	Item2                          int
	Item3                          int
	Item4                          int
	Item5                          int
	Item6                          int
	ItemsPurchased                 int
	KillingSprees                  int
	Kills                          int
	Lane                           string
	LargestCriticalStrike          int
	LargestKillingSpree            int
	LargestMultiKill               int
	LongestTimeSpentLiving         int
	MagicDamageDealt               int
	MagicDamageDealtToChampions    int
	MagicDamageTaken               int
	NeutralMinionsKilled           int
	NeedVisionPings                int
	NexusKills                     int
	NexusTakedowns                 int
	NexusLost                      int
	ObjectivesStolen               int
	ObjectivesStolenAssists        int
	OnMyWayPings                   int
	ParticipantId                  int
	PlayerScore0                   float64
	PlayerScore1                   float64
	PlayerScore2                   float64
	PlayerScore3                   float64
	PlayerScore4                   float64
	PlayerScore5                   float64
	PlayerScore6                   float64
	PlayerScore7                   float64
	PlayerScore8                   float64
	PlayerScore9                   float64
	PlayerScore10                  float64
	PlayerScore11                  float64
	PentaKills                     int
	PhysicalDamageDealt            int
	PhysicalDamageDealtToChampions int
	PhysicalDamageTaken            int
	Placement                      int
	PlayerAugment1                 int
	PlayerAugment2                 int
	PlayerAugment3                 int
	PlayerAugment4                 int
	PlayerSubteamId                int
	PushPings                      int
	ProfileIcon                    int
	Puuid                          string
	QuadraKills                    int
	RiotIdGameName                 string
	RiotIdTagline                  string
	Role                           string
	SightWardsBoughtInGame         int
	Spell1Casts                    int
	Spell2Casts                    int
	Spell3Casts                    int
	Spell4Casts                    int
	SubteamPlacement               int
	Summoner1Casts                 int
	Summoner1Id                    int
	Summoner2Casts                 int
	Summoner2Id                    int
	SummonerId                     string
	SummonerLevel                  int
	SummonerName                   string
	TeamEarlySurrendered           bool
	TeamId                         int
	TeamPosition                   string
	TimeCCingOthers                int
	TimePlayed                     int
	TotalAllyJungleMinionsKilled   int
	TotalDamageDealt               int
	TotalDamageDealtToChampions    int
	TotalDamageShieldedOnTeammates int
	TotalDamageTaken               int
	TotalEnemyJungleMinionsKilled  int
	TotalHeal                      int
	TotalHealsOnTeammates          int
	TotalMinionsKilled             int
	TotalTimeCCDealt               int
	TotalTimeSpentDead             int
	TotalUnitsHealed               int
	TripleKills                    int
	TrueDamageDealt                int
	TrueDamageDealtToChampions     int
	TrueDamageTaken                int
	TurretKills                    int
	TurretTakedowns                int
	TurretsLost                    int
	UnrealKills                    int
	VisionScore                    int
	VisionClearedPings             int
	VisionWardsBoughtInGame        int
	WardsKilled                    int
	WardsPlaced                    int
	Win                            bool
}
